### ISSUE TITLE
Persistent Template Noise with SciPy>=1.8

### ISSUE THREAD

**Issue by Alexis-Melot** [alejoe91/MEArec#99] opened 2022-02-22 21:04 UTC
I'm trying to simulate a simple experimental environment with 1 electrode and 2 excitatory neurons (Allen models) and with no noise.
I've attached my script :
[simAllen.txt](https://github.com/alejoe91/MEArec/files/8120118/simAllen.txt)
and the recording parameters :
[rec_params.txt](https://github.com/alejoe91/MEArec/files/8120109/rec_params.txt)

Somehow, I can't remove the noise on the templates (picture below), and I don't understand where it's coming from : 
![MEArec_rec](https://user-images.githubusercontent.com/87820482/155217778-fdfed035-2ba8-4e3b-b2b8-9f35bb997cfa.png)

I checked my NEURON intracellular folder and it is empty after I run my script.

But here are the templates after calling `mr.TemplateGenerator()`:
![MEArec_cleantemplates](https://user-images.githubusercontent.com/87820482/155218913-34defc29-2dd3-4b78-b490-0558995470a3.png)
and after calling `mr.gen_recordings()` with the above generated templates:
![MEArec_noisyTemplate_raster](https://user-images.githubusercontent.com/87820482/155219054-c7fc7ac8-579b-4eb1-935b-b4dca36b7df3.png)

**Comment by alejoe91** [comment] 2022-02-23 08:51
Hi @Alexis-Melot 

Based on you params, it might be related to the filter option! `rec_params['recordings']['filter_cutoff'] = [300,490000]`
I guess the lowpass value is off. Maybe try 6000? Can you also try to run with `rec_params['recordings']['filter'] = False` to make sure the problem is the filtering step?

Cheers
Alessio

**Comment by Alexis-Melot** [comment] 2022-02-24 18:11
Hi @alejoe91 
So I tried cutoff frequencies [300,1000] and [300,3000] for a sampling frequency of 10kHz, and here are the plots of the generated recording:
[300,1000] :
![recordings_filt_300_1000](https://user-images.githubusercontent.com/87820482/155582544-1829fe32-cc2a-4d25-895c-920134088d32.png)
[300,3000] :
![recordings_filt_300_3000](https://user-images.githubusercontent.com/87820482/155582562-e8b9b3b2-9fdf-4ff6-8802-f4947d7c196e.png)
and no filtering:
![recordings_not_filt](https://user-images.githubusercontent.com/87820482/155582583-6e28241b-76e4-4b02-9151-1f817511776c.png)

**Comment by alejoe91** [comment] 2022-02-24 18:49
Can you try to leave the sampling frequency to default (`None`)? Might be a resampling issue

**Comment by Alexis-Melot** [comment] 2022-02-24 19:25
Actually the `fs` recordings parameter was already `None`. It was the `dt` for the template generator that I set to `0.1ms`.
But here is the recording when `dt` template param is set to default :
not filtered:
![rec_not_filt_dt_default](https://user-images.githubusercontent.com/87820482/155591857-3e04fe62-452d-4e7b-930a-b971651de320.png)
[300,1000] filtered with filter order 30 :
![rec_filt_300_1000_order30](https://user-images.githubusercontent.com/87820482/155593263-905dad75-1be9-4f0e-94da-786feeb1c12b.png)

**Comment by alejoe91** [comment] 2022-03-09 15:35
Hi @Alexis-Melot 

I think that the problem was introduced with `scipy==1.8` release! Still have to investigate further why this is happening, but for now can you try to downgrade scipy to 1.7? Let me know if this temporarily fixes the issue.

**Comment by Alexis-Melot** [comment] 2022-03-16 00:05
Thanks ! it worked perfectly !

**Comment by alejoe91** [comment] 2022-03-16 07:12
Awesome! I'll keep this open until I understand why this is happening and I fix it also for the latest scipy versions

**Comment by alejoe91** [comment] 2022-07-18 15:48
Closed via https://github.com/alejoe91/MEArec/pull/116

**Closed by alejoe91** 2022-07-18 15:48 UTC
